{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "ccc6d0bb-10e8-46ca-8bc0-c6632605cf84",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import tkinter as tk\n",
    "from tkinter import messagebox\n",
    "import csv\n",
    "from PIL import Image, ImageTk\n",
    "\n",
    "# 🔹 Set Paths\n",
    "downloads_folder = os.path.join(os.path.expanduser(\"~\"), \"Downloads\", \"CareerUpskillers\")\n",
    "pdf_path = os.path.join(downloads_folder, \"pdf.pdf\")\n",
    "leads_csv = os.path.join(downloads_folder, \"leads.csv\")\n",
    "\n",
    "# 🔹 Ensure CareerUpskillers directory exists\n",
    "if not os.path.exists(downloads_folder):\n",
    "    os.makedirs(downloads_folder)\n",
    "\n",
    "# 🔹 Ensure CSV file exists for lead storage\n",
    "if not os.path.exists(leads_csv):\n",
    "    with open(leads_csv, \"w\", newline=\"\") as f:\n",
    "        writer = csv.writer(f)\n",
    "        writer.writerow([\"Name\", \"Email\", \"Phone\", \"Experience\", \"Domain\", \"Location\", \"Current Salary\", \n",
    "                         \"Expected Salary\", \"Upwork/Fiverr (Yes/No)\", \"AI Business Interest (Yes/No)\"])\n",
    "\n",
    "# 🔹 Check Brochure Function\n",
    "def check_brochure():\n",
    "    if os.path.exists(pdf_path):\n",
    "        messagebox.showinfo(\"Success\", \"Thank you! Your brochure will now download.\")\n",
    "        os.startfile(pdf_path)  # Open the PDF\n",
    "    else:\n",
    "        messagebox.showerror(\"Error\", \"Brochure not found! Please add 'pdf.pdf' in CareerUpskillers folder.\")\n",
    "\n",
    "# 🔹 Lead Collection Function\n",
    "def submit_lead():\n",
    "    name = name_entry.get()\n",
    "    email = email_entry.get()\n",
    "    phone = phone_entry.get()\n",
    "    experience = experience_entry.get()\n",
    "    domain = domain_entry.get()\n",
    "    location = location_entry.get()\n",
    "    current_salary = current_salary_entry.get()\n",
    "    expected_salary = expected_salary_entry.get()\n",
    "    upwork_fiverr = upwork_fiverr_var.get()\n",
    "    ai_business_interest = ai_business_interest_var.get()\n",
    "\n",
    "    if not email or len(phone) < 10:\n",
    "        messagebox.showerror(\"Error\", \"Valid Email & 10-digit Phone are required to download!\")\n",
    "        return\n",
    "\n",
    "    with open(leads_csv, \"a\", newline=\"\") as f:\n",
    "        writer = csv.writer(f)\n",
    "        writer.writerow([name, email, phone, experience, domain, location, current_salary, expected_salary,\n",
    "                         upwork_fiverr, ai_business_interest])\n",
    "\n",
    "    messagebox.showinfo(\"Success\", \"Thank you! Click 'Download Brochure' now.\")\n",
    "    download_btn.config(state=tk.NORMAL)  # Enable download after submission\n",
    "\n",
    "# 🔹 GUI Setup\n",
    "root = tk.Tk()\n",
    "root.title(\"CareerUpskillers - We Help you grow\")\n",
    "root.geometry(\"400x600\")\n",
    "\n",
    "# 🔹 Load Logo\n",
    "logo_path = \"careerupskillers logo.jpg\"\n",
    "if os.path.exists(logo_path):\n",
    "    logo = Image.open(logo_path).resize((150, 150), Image.LANCZOS)\n",
    "    logo = ImageTk.PhotoImage(logo)\n",
    "    tk.Label(root, image=logo).pack()\n",
    "\n",
    "# 🔹 Form Fields\n",
    "tk.Label(root, text=\"Name:\").pack()\n",
    "name_entry = tk.Entry(root)\n",
    "name_entry.pack()\n",
    "\n",
    "tk.Label(root, text=\"Email:\").pack()\n",
    "email_entry = tk.Entry(root)\n",
    "email_entry.pack()\n",
    "\n",
    "tk.Label(root, text=\"Phone:\").pack()\n",
    "phone_entry = tk.Entry(root)\n",
    "phone_entry.pack()\n",
    "\n",
    "tk.Label(root, text=\"Experience (Years):\").pack()\n",
    "experience_entry = tk.Entry(root)\n",
    "experience_entry.pack()\n",
    "\n",
    "tk.Label(root, text=\"Domain:\").pack()\n",
    "domain_entry = tk.Entry(root)\n",
    "domain_entry.pack()\n",
    "\n",
    "tk.Label(root, text=\"Location:\").pack()\n",
    "location_entry = tk.Entry(root)\n",
    "location_entry.pack()\n",
    "\n",
    "tk.Label(root, text=\"Current Salary:\").pack()\n",
    "current_salary_entry = tk.Entry(root)\n",
    "current_salary_entry.pack()\n",
    "\n",
    "tk.Label(root, text=\"Expected Salary:\").pack()\n",
    "expected_salary_entry = tk.Entry(root)\n",
    "expected_salary_entry.pack()\n",
    "\n",
    "# 🔹 Upwork/Fiverr Question\n",
    "tk.Label(root, text=\"Do you have Upwork or Fiverr?\").pack()\n",
    "upwork_fiverr_var = tk.StringVar(value=\"No\")\n",
    "tk.Radiobutton(root, text=\"Yes\", variable=upwork_fiverr_var, value=\"Yes\").pack()\n",
    "tk.Radiobutton(root, text=\"No\", variable=upwork_fiverr_var, value=\"No\").pack()\n",
    "\n",
    "# 🔹 AI Business Interest Question\n",
    "tk.Label(root, text=\"Interested in building your own AI business agents?\").pack()\n",
    "ai_business_interest_var = tk.StringVar(value=\"No\")\n",
    "tk.Radiobutton(root, text=\"Yes\", variable=ai_business_interest_var, value=\"Yes\").pack()\n",
    "tk.Radiobutton(root, text=\"No\", variable=ai_business_interest_var, value=\"No\").pack()\n",
    "\n",
    "# 🔹 Submit Button (Collects Leads)\n",
    "submit_btn = tk.Button(root, text=\"Submit & Unlock Brochure\", command=submit_lead)\n",
    "submit_btn.pack()\n",
    "\n",
    "# 🔹 Download Button (Initially Disabled)\n",
    "download_btn = tk.Button(root, text=\"Download Brochure\", command=check_brochure, state=tk.DISABLED)\n",
    "download_btn.pack()\n",
    "\n",
    "# 🔹 Run App\n",
    "root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
<<<<<<< HEAD
   "execution_count": none,
=======
   "execution_count": None,
   "id": "2324b4da-913f-4e17-a073-3d2ada7b4927",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
